SpaceAgency.Intranet/Controllers/MainContentController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SpaceAgency.Data.Data;
using SpaceAgency.Data.Data.CMS;
using SpaceAgency.Intranet.TwoViews;

namespace SpaceAgency.Intranet.Controllers
{
    public class MainContentController : Controller
    {
        private readonly SpaceAgencyContext _context;

        public MainContentController(SpaceAgencyContext context)
        {
            _context = context;
        }

        // GET: Structure
        public async Task<IActionResult> Index()
        {
            var model = new TwoViewsAtOnce()
            {
                MainContents = await _context.MainContent.ToListAsync()
            };
            return View(model);
        }

        // GET: Structure/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var MainContent = await _context.MainContent.FindAsync(id);
            model.MainContent = MainContent;

            return PartialView(model);
        }

        // GET: Structure/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Structure/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMainContent,Icon,Header,Content")] MainContent mainContent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mainContent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var MainContent = await _context.MainContent.FindAsync(id);
            model.MainContent = MainContent;

            return PartialView(model);
        }

        // POST: Structure/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMainContent,Icon,Header,Content")] MainContent mainContent)
        {
            if (id != mainContent.IdMainContent)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mainContent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MainContentExists(mainContent.IdMainContent))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Structure/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var MainContent = await _context.MainContent.FindAsync(id);
            model.MainContent = MainContent;

            return PartialView(model);
        }

        // POST: Structure/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var MainContent = await _context.MainContent.FindAsync(id);
            _context.MainContent.Remove(MainContent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MainContentExists(int id)
        {
            return _context.MainContent.Any(e => e.IdMainContent == id);
        }
    }
}

SpaceAgency.Intranet/Controllers/PageController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SpaceAgency.Data.Data;
using SpaceAgency.Data.Data.CMS;
using SpaceAgency.Intranet.TwoViews;

namespace SpaceAgency.Intranet.Controllers
{
    public class PageController : Controller
    {
        private readonly SpaceAgencyContext _context;

        public PageController(SpaceAgencyContext context)
        {
            _context = context;
        }

        // GET: page
        public async Task<IActionResult> Index()
        {
            var model = new TwoViewsAtOnce()
            {
                Pages = await _context.Page.ToListAsync()
            };
            return View(model);
        }

        /*// GET: page/Details/5                 ///"Mrówkowa" wersja Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.page
                .FirstOrDefaultAsync(m => m.Idpage == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }*/

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var page = await _context.Page.FindAsync(id);
            model.Page = page;

            return PartialView(model);
        }

        // GET: page/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: page/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPage,Title,Header,TopContent,BotContent")] Page page)
        {
            if (ModelState.IsValid)
            {
                _context.Add(page);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        /*// GET: page/Edit/5                 ///"Mrówkowa" wersja Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.page.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }*/

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var page = await _context.Page.FindAsync(id);
            model.Page = page;

            return PartialView(model);
        }

        // POST: page/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPage,Title,Header,TopContent,BotContent")] Page page)
        {
            if (id != page.IdPage)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(page);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.IdPage))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: page/Delete/5                 ///"Mrówkowa" wersja Delete
        /*public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.page
                .FirstOrDefaultAsync(m => m.Idpage == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }*/

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var page = await _context.Page.FindAsync(id);
            model.Page = page;

            return PartialView(model);
        }

        // POST: page/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Page.FindAsync(id);
            _context.Page.Remove(page);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Page.Any(e => e.IdPage == id);
        }
    }
}

SpaceAgency.Intranet/Controllers/PioneerController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SpaceAgency.Data.Data;
using SpaceAgency.Data.Data.CMS;
using SpaceAgency.Intranet.TwoViews;

namespace SpaceAgency.Intranet.Controllers
{
    public class PioneerController : Controller
    {
        private readonly SpaceAgencyContext _context;

        public PioneerController(SpaceAgencyContext context)
        {
            _context = context;
        }

        // GET: Pioneer
        public async Task<IActionResult> Index()
        {
            var model = new TwoViewsAtOnce()
            {
                Pioneers = await _context.Pioneer.ToListAsync()
            };
            return View(model);
        }

        // GET: Pioneer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var Pioneer = await _context.Pioneer.FindAsync(id);
            model.Pioneer = Pioneer;

            return PartialView(model);
        }

        // GET: Pioneer/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Pioneer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPioneer,Name,SurName,Status,CurrentPlanet")] Pioneer Pioneer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Pioneer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var Pioneer = await _context.Pioneer.FindAsync(id);
            model.Pioneer = Pioneer;

            return PartialView(model);
        }

        // POST: Pioneer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPioneer,Name,SurName,Status,CurrentPlanet")] Pioneer Pioneer)
        {
            if (id != Pioneer.IdPioneer)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Pioneer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PioneerExists(Pioneer.IdPioneer))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Pioneer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return PartialView();
            }
            var model = new TwoViewsAtOnce();
            var Pioneer = await _context.Pioneer.FindAsync(id);
            model.Pioneer = Pioneer;

            return PartialView(model);
        }

        // POST: Pioneer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Pioneer = await _context.Pioneer.FindAsync(id);
            _context.Pioneer.Remove(Pioneer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PioneerExists(int id)
        {
            return _context.Pioneer.Any(e => e.IdPioneer == id);
        }
    }
}

SpaceAgency.Intranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceAgency.Intranet</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
    <!-- End plugin css for this page -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
</head>
<body>
   <div class="container-scroller">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
          <a class="sidebar-brand brand-logo mdi mdi-rocket btn btn-primary" href="@Url.ActionLink("Index", "Home")">SpaceAdmin</a>
          <a class="sidebar-brand brand-logo-mini mdi mdi-rocket btn btn-primary" href="@Url.ActionLink("Index", "Home")"></a>
        </div>
        <ul class="nav">

          <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.ActionLink("Index", "Home")">
              <span class="menu-icon">
                <i class="mdi mdi-rocket"></i>
              </span>
              <span class="menu-title">Main</span>
            </a>
          </li>

          <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#Missions" aria-expanded="false" aria-controls="Missions">
              <span class="menu-icon">
                <i class="mdi mdi-satellite-variant"></i>
              </span>
              <span class="menu-title">Missions</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="Missions">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Gliese_667Cc", "Home")">Gliese-667Cc</a></li>
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Kepler_22B", "Home")">Kepler-22B</a></li>
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Kepler_69c", "Home")">Kepler-69c</a></li>
              </ul>
            </div>
          </li>

          <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#DataEdit" aria-expanded="false" aria-controls="DataEdit">
              <span class="menu-icon">
                <i class="mdi mdi-settings"></i>
              </span>
              <span class="menu-title">DataEdit</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="DataEdit">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Index", "Page")">Page</a></li>
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Index", "Pioneer")">Pioneer</a></li>
                <li class="nav-item"> <a class="nav-link" href="@Url.ActionLink("Index", "MainContent")">Main Content</a></li>
              </ul>
            </div>
          </li>

        </ul>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar p-0 fixed-top d-flex flex-row">
          <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="@Url.ActionLink("Index", "Home")"></a>
          </div>
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
              <span class="mdi mdi-menu"></span>
            </button>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="mdi mdi-format-line-spacing"></span>
            </button>
          </div>
        </nav>
        <!-- partial -->
        <div class="main-panel">
            
          @RenderBody()
          
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">SpaceAdmin is part of EasySpaceSpeed Company</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Developer - Rafał Olejniczak</a> </span>
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- Jquerry MUST BE FIRST -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- end Jquerry -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/assets/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/assets/js/dashboard.js"></script>
    <script src="~/assets/js/chart.js"></script>
    <script src="~/js/site.js"></script>
    <!-- End custom js for this page -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>