SpaceAgency.SiteWWW/Models/BusinessLogic/TravelOrderB.cs
using Microsoft.EntityFrameworkCore;
using SpaceAgency.Data.Data;
using SpaceAgency.Data.Data.Travels;

namespace SpaceAgency.SiteWWW.Models.BusinessLogic
{
    public class TravelOrderB
    {
        private readonly SpaceAgencyContext _context;
        private string idOrderSesion;

        public TravelOrderB(SpaceAgencyContext context, HttpContext httpContext)
        {
            _context = context;
            idOrderSesion = GetIdOrderSesion(httpContext);
        }

        private string GetIdOrderSesion(HttpContext httpContext)
        {
            if(httpContext.Session.GetString("IdOrderSesion") == null)
            {
                if(!string.IsNullOrWhiteSpace(httpContext.User.Identity.Name))
                {
                    httpContext.Session.SetString("IdOrderSesion", httpContext.User.Identity.Name);
                }
                else
                {
                    Guid tempIdOrderSesion = Guid.NewGuid();
                    httpContext.Session.SetString("IdOrderSesion", tempIdOrderSesion.ToString());
                }
            }
            return httpContext.Session.GetString("IdOrderSesion").ToString();
        }

        public void AddToOrder(Travel travel)
        {
            var tempTravelOrder =
                _context.TravelOrder
                .Where(e => e.IdTravelSesion == idOrderSesion && e.IdTravel == travel.IdTravel)
                .FirstOrDefault();

            if(tempTravelOrder != null)
            {
                tempTravelOrder.Seats++;
            }
            else
            {
                tempTravelOrder = new TravelOrder()
                {
                    IdTravelSesion = idOrderSesion,
                    IdTravel = travel.IdTravel,
                    Travel = _context.Travel.Find(travel.IdTravel),
                    Seats = 1,
                    CreationDate = DateTime.Now
                };
                _context.TravelOrder.Add(tempTravelOrder);
            }
            _context.SaveChanges();
        }

        public void RemoveFromOrder(Travel travel)
        {
            var tempTravelOrder =
                _context.TravelOrder
                .Where(e => e.IdTravelSesion == idOrderSesion && e.IdTravel == travel.IdTravel)
                .FirstOrDefault();

            if (tempTravelOrder != null)
            {
                tempTravelOrder.Seats--;
                if (tempTravelOrder.Seats <= 0)
                {
                    _context.TravelOrder.Remove(tempTravelOrder);
                }
            }
            _context.SaveChanges();
        }

        public async Task<List<TravelOrder>> GetTravelOrderClient()
        {
            return await _context.TravelOrder.Where(e => e.IdTravelSesion == this.idOrderSesion).Include(e => e.Travel).ToListAsync();
        }
    }
}

SpaceAgency.SiteWWW/Models/ErrorViewModel.cs
namespace SpaceAgency.SiteWWW.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SpaceAgency.SiteWWW/Models/TravelOrders/DataToOrder.cs
using SpaceAgency.Data.Data.Travels;

namespace SpaceAgency.SiteWWW.Models.TravelOrders
{
    public class DataToOrder
    {
        public List<TravelOrder> TravelOrders { get; set; }
    }
}

SpaceAgency.SiteWWW/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SpaceAgency.Data.Data;
using SpaceAgency.SiteWWW.Models;
using System.Diagnostics;

namespace SpaceAgency.SiteWWW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SpaceAgencyContext _context;

        public HomeController(SpaceAgencyContext context)
        {
            _context = context;
        }

        public IActionResult Index(int? id)
        {
            ViewBag.ModelPages =
                (
                    from page in _context.Page
                    select page
                ).ToList();

            ViewBag.ModelMainContent =
                (
                    from mainContent in _context.MainContent
                    select mainContent
                ).ToList();

            if (id == null)
            {
                id = _context.Page.First().IdPage;
            }
            var item = _context.Page.Find(id);

            return View(item);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult JoinUs()
        {
            return View();
        }
        
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpaceAgency.SiteWWW/Controllers/SpaceOffersController.cs
using SpaceAgency.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SpaceAgency.SiteWWW.Controllers
{
    public class SpaceOffersController : Controller
    {
        private readonly SpaceAgencyContext _context;

        public SpaceOffersController(SpaceAgencyContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {
            ViewBag.ModelRockets = await _context.Planet.ToListAsync();

            if (id == null)
            {
                var first = await _context.Planet.FirstAsync();
                id = first.IdPlanet;
            }

            return View(await _context.Travel.Where(t => t.IdRocket == id).ToListAsync());
        }

        public async Task<IActionResult> MoreInfo(int? id)
        {
            ViewBag.ModelRockets = await _context.Planet.ToListAsync();
            return View(await _context.Travel.Where(t => t.IdTravel == id).FirstOrDefaultAsync());
        }
    }
}

SpaceAgency.SiteWWW/Controllers/TravelOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpaceAgency.Data.Data;
using SpaceAgency.SiteWWW.Models.BusinessLogic;
using SpaceAgency.SiteWWW.Models.TravelOrders;

namespace SpaceAgency.SiteWWW.Controllers
{
    public class TravelOrderController : Controller
    {
        private readonly SpaceAgencyContext _context;

        public TravelOrderController(SpaceAgencyContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.ModelRockets = await _context.Planet.ToListAsync();

            TravelOrderB travelOrderB = new TravelOrderB(_context, this.HttpContext);
            DataToOrder dataToOrder = new DataToOrder()
            {
                TravelOrders = await travelOrderB.GetTravelOrderClient()
            };
            return View(dataToOrder);
        }

        public async Task<IActionResult> AddToOrder(int id)
        {
            TravelOrderB travelOrderB = new TravelOrderB(_context, this.HttpContext);
            travelOrderB.AddToOrder(await _context.Travel.FindAsync(id));
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveFromOrder(int id)
        {
            TravelOrderB travelOrderB = new TravelOrderB(_context, this.HttpContext);
            travelOrderB.RemoveFromOrder(await _context.Travel.FindAsync(id));
            return RedirectToAction("Index");
        }
    }
}

SpaceAgency.SiteWWW/Views/Home/About.cshtml
@{
    ViewData["Title"] = "SpaceAgency";
}

 <div class="section">

      <!--   Icon Section   -->
      <div class="row">

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="~/Gliese_667Cc.jpg">
              <span class="card-title">Gliese-667Cc</span>
            </div>
            <div class="card-content">
              <p>Gliese 667 Cc is an exoplanet orbiting within the habitable zone of the red dwarf star Gliese 667 C, 
                  which is a member of the Gliese 667 triple star system, approximately 23.62 light-years (7.24 parsecs; 223.5 trillion kilometres)
                  away in the constellation of Scorpius. Temperatues of this planets are similar to our earth like. <br> <br>
                  Our Pioneers main mission will be searching for possible resources and preparing save habitants for future missions. </p>
            </div>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="~/KEPLER_22B.jpg">
              <span class="card-title">Kepler-22b</span>
            </div>
            <div class="card-content">
              <p>Kepler-22b is an exoplanet orbiting within the habitable zone of the Sun-like star Kepler-22.
                  It is located about 600 light-years (180 pc) from Earth in the constellation of Cygnus.
                  It was discovered by NASA's Kepler Space Telescope in December 2011 and was the first known transiting planet to orbit within the habitable zone of a Sun-like star. <br> <br>
                  Main goal will be prepare this planet as new Humankind home hover if our Pioneers will find any rare resources they will be able to set up small eco friendly mines.</p>
            </div>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="~/Kepler-69c.jpg">
              <span class="card-title">Kepler-69c</span>
            </div>
            <div class="card-content">
              <p>Kepler-69c is a confirmed super-Earth extrasolar planet, likely rocky, orbiting the Sun-like star Kepler-69, the outermore of two such planets discovered by NASA's Kepler spacecraft. 
                  It is located about 2,430 light-years (746 parsecs) from Earth. <br> <br>
                  This mission will require from our Pioneers to focus on maximum efficiency, mining and factory optimalization.
                  There is no need to be eco friendly on this planet. We are not planing to make this planet anything more than Humankind biggest mine </p>
            </div>
          </div>
        </div>

      </div>

 </div>

SpaceAgency.SiteWWW/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "SpaceAgency";
}

 <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">call</i></h2>
            <h5 class="center">Call Us</h5>

            <p class="light">Please call 8:00 - 16:00. +48 111 222 333 - Office <br>
                             Please call 10:00 - 20:00. +48 111 222 334 - Sales </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">email</i></h2>
            <h5 class="center">Email Us</h5>

            <p class="light">Answer in 24h - EasySpaceSpeed@gmail.com <br>
                             Answer in 12h -JoinSpacePioneers@gmail.com </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">build</i></h2>
            <h5 class="center">Support</h5>

            <p class="light"> +48 111 222 555 - Questions about Joining <br>
                              +48 111 222 666 - Page technical support </p>
          </div>
        </div>
      </div>

 </div>

SpaceAgency.SiteWWW/Views/Home/JoinUs.cshtml
@{
    ViewData["Title"] = "SpaceAgency";
}

 <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">To Be Done</h5>

            <p class="light">Planuję tu zrobić jakiś formularz do dodawania się do bazy danych osób chętnych do zapisania się.
                Następnie już z poziomu intranetu będzie można potwierdzać lub odrzucać takie zgłoszenia. Nie mam jednak jeszcze ściśle określonego layoutu.
                Zrobię to jak będę posiadał więcej wiedzy z przyszłych wykładów. Potrzebuje ogólnego spojrzenia.</p>
          </div>
        </div>

        <div class="col s12 m4">
        </div>
      </div>

 </div>

SpaceAgency.SiteWWW/Views/Shared/MainContent.cshtml
@model IEnumerable<SpaceAgency.Data.Data.CMS.MainContent>

<!--Ikony - settings, group, flash_on-->

 <div class="section">

      <div class="row">
          @foreach(var item in Model)
          {
              <div class="col s12 m4">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="material-icons">@item.Icon</i></h2>
                  <h5 class="center">@item.Header</h5>

                  <p class="light">@item.Content</p>
                </div>
              </div>
          }
        

      </div>

 </div>

SpaceAgency.SiteWWW/Views/Shared/Pages.cshtml
@model IEnumerable<SpaceAgency.Data.Data.CMS.Page>

<a id="logo-container" href="~/" class="brand-logo">EasySpaceSpeed</a>
<ul class="right hide-on-med-and-down">
    @foreach(var item in Model)
    {
        <li>@Html.ActionLink(item.Header, "Index", "Home", new {id = item.IdPage}, null)</li>
    }
    <li>@Html.ActionLink("Space Travel", "Index", "SpaceOffers")</li>
</ul>

<ul id="nav-mobile" class="sidenav">
    <li><a href="#">Navbar Link</a></li>
</ul>
<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>

SpaceAgency.SiteWWW/Views/Shared/RocketsMenu.cshtml
@model IEnumerable<SpaceAgency.Data.Data.Travels.Planet>

<a id="logo-container" href="~/" class="brand-logo">EasySpaceSpeed</a>



<ul class="right hide-on-med-and-down">
    @foreach(var item in Model)
    {
        <li>@Html.ActionLink(item.Name, "Index", "SpaceOffers", new {id = item.IdPlanet}, null)</li>
    }
    <li><a asp-action="Index" asp-controller="TravelOrder">Ordered Tickets</a></li>
</ul>

<ul id="nav-mobile" class="sidenav">
    <li><a href="#">Navbar Link</a></li>
</ul>
<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>

SpaceAgency.SiteWWW/Views/Shared/_Layout.cshtml
@model SpaceAgency.Data.Data.CMS.Page

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceAgency.SiteWWW</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
  <nav class="blue darken-3" role="navigation">
    <div class="nav-wrapper container">
      @await Html.PartialAsync("Pages",(IEnumerable<SpaceAgency.Data.Data.CMS.Page>)ViewBag.ModelPages)
    </div>
  </nav>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">@Model.Header</h1>
        <div class="row center">
          <h5 class="header col s12 light">@Model.TopContent</h5>
        </div>
        <br><br>
      </div>
    </div>
    <div class="parallax"><img src="~/background1.jpg" alt="Unsplashed background img 1"></div>
  </div>

  @RenderBody() <!--To nic nie robi u mnie bo były konflikty w typie danych, przeniosłem zawartość do "MainContent"-->

  <div class="container grey lighten-1">
    <div class="section">
        @await Html.PartialAsync("MainContent",(IEnumerable<SpaceAgency.Data.Data.CMS.MainContent>)ViewBag.ModelMainContent)
    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="parallax"><img src="~/background2.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <footer class="page-footer blue darken-3">
    <div class="container">
      <div class="row">
          <h5 class="white-text">@Model.BotContent </h5>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3">Rafał Olejniczak</a>
      </div>
    </div>
  </footer>
    
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="/js/materialize.js"></script>
    <script src="/js/init.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SpaceAgency.SiteWWW/Views/Shared/_SpaceOffersLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceAgency.SiteWWW</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
  <nav class="blue darken-3" role="navigation">
    <div class="nav-wrapper container">
      @await Html.PartialAsync("RocketsMenu",(IEnumerable<SpaceAgency.Data.Data.Travels.Planet>)ViewBag.ModelRockets)
    </div>
  </nav>

  @RenderBody()

  <footer class="page-footer blue darken-3">
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3">Rafał Olejniczak</a>
      </div>
    </div>
  </footer>
    
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="/js/materialize.js"></script>
    <script src="/js/init.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SpaceAgency.SiteWWW/Views/Shared/_TravelOrderLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceAgency.SiteWWW</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
  <nav class="blue darken-3" role="navigation">
    <div class="nav-wrapper container">
      @await Html.PartialAsync("RocketsMenu",(IEnumerable<SpaceAgency.Data.Data.Travels.Planet>)ViewBag.ModelRockets)
    </div>
  </nav>

  @RenderBody()

  <footer class="page-footer blue darken-3">
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3">Rafał Olejniczak</a>
      </div>
    </div>
  </footer>
    
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="/js/materialize.js"></script>
    <script src="/js/init.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SpaceAgency.SiteWWW/Views/SpaceOffers/Index.cshtml
@model IEnumerable<SpaceAgency.Data.Data.Travels.Travel>
@{
    ViewData["Title"] = "Rockets";
    Layout = "~/Views/Shared/_SpaceOffersLayout.cshtml";
}
<div>
    <div class="section">
      <br><br>
      <div class="center-align">
          <div id="index-banner" class="parallax-container">
              <div class="container">
                  @foreach(var travel in Model)
                  {
                      <img src= @( "/" + travel.Planet.Name + ".png") alt="">
                      break;
                  }
              </div>
          <div class="parallax"><img src="~/Space.jpg" alt="Unsplashed background img 1"></div>
          </div>
      </div>
      <div class="container">
        <br>
        <ul class="collection">
            @foreach(var travel in Model)
            {
                <li class="collection-item avatar hoverable light-blue lighten-5">
                  <img src= @( "/" + travel.Planet.Name + ".jpg") alt="" class="circle">
                  <span class="title hoverable">@Html.ActionLink(travel.Name, "MoreInfo", "SpaceOffers", new {id=travel.IdTravel}, null)</span>
                  <p>Seats - @travel.Seats <br>
                     Time off Earth - @travel.TimeOffEarth
                  </p>
                </li>
            }
        </ul>
        <br><br>
      </div>
    </div>
</div>

SpaceAgency.SiteWWW/Views/SpaceOffers/MoreInfo.cshtml
@model SpaceAgency.Data.Data.Travels.Travel
@{
    ViewData["Title"] = "MoreInfo";
    Layout = "~/Views/Shared/_SpaceOffersLayout.cshtml";
}

<div id="index-banner" class="parallax-container">

<div class="container">
  <div class="row">
    <div class="col s12">
      <h1 class="center-align">@Model.Name</h1>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
    
      <div class="col s7">
        <div class="center-align"> <img src= @( "/" + Model.Planet.Name + ".png") alt="" class="poster"> </div>
      </div>
      
      <div class="col s5">
      @{await Html.RenderPartialAsync("MoreInfoData");}
      </div>
    
    </div>
</div>

<div class="parallax"><img src="~/Space.jpg" alt=""></div>
</div>

SpaceAgency.SiteWWW/Views/SpaceOffers/MoreInfoData.cshtml
@model SpaceAgency.Data.Data.Travels.Travel
@{
    ViewData["Title"] = "MoreInfoData";
}

<div class="col s12 m12 l1">
   <img src="~/window_transparent.png" alt="">
</div>

<div class="col s12 m12 l11">

    <div class="section blue-text text-darken-1">
      <div class="container">
        <h3 class="title">@Model.Name</h3>
        <h5>Destination - @Model.Planet.Name <br>
           Type - @Model.Type <br>
           Seats - @Model.Seats <br>
           Time off Earth - @Model.TimeOffEarth
        </h5>
        <h3 class="title">About @Model.Planet.Name</h3>
        <h5>Type - @Model.Planet.Type <br>
           Security Level - @Model.Planet.SecurityLevel <br>
           Status - @Model.Planet.Status
           <br>
        </h5>
        <a asp-action="AddToOrder" asp-controller="TravelOrder" asp-route-id="@Model.IdTravel" 
            class="btn waves-effect waves-light" type="submit">Buy a Ticket
            <i class="material-icons right">send</i>
        </a>
        <br><br><br>
      </div>
    </div>

</div>

SpaceAgency.SiteWWW/Views/TravelOrder/Index.cshtml
@model SpaceAgency.SiteWWW.Models.TravelOrders.DataToOrder
@{
    ViewData["Title"] = "Travels";
    Layout = "~/Views/Shared/_TravelOrderLayout.cshtml";
}

<div>
    <div class="section">
      <br><br>
      <div class="center-align">
          <div id="index-banner" class="parallax-container">
              <div class="container">
                  <img src= @( "/blackRocket.png") alt="">
              </div>
          <div class="parallax"><img src="~/Space.jpg" alt="Unsplashed background img 1"></div>
          </div>
      </div>
      <div class="container">
        <br>
        <ul class="collection">
            @foreach(var travel in Model.TravelOrders)
            {
                <li class="collection-item avatar hoverable light-blue lighten-5">
                  <img src= @( "/" + travel.Travel.Planet.Name + ".jpg") alt="" class="circle">
                  <span class="title hoverable">@Html.ActionLink(travel.Travel.Name, "MoreInfo", "SpaceOffers", new {id=travel.IdTravel}, null)</span>
                  <p>Seats - @travel.Seats <br>
                     Time off Earth - @travel.Travel.TimeOffEarth
                  </p>
                  <a asp-action="AddToOrder" asp-controller="TravelOrder" asp-route-id="@travel.IdTravel" class="btn-floating btn-small waves-effect waves-light blue"><i class="material-icons">add</i></a>
                  <a asp-action="RemoveFromOrder" asp-controller="TravelOrder" asp-route-id="@travel.IdTravel" class="btn-floating btn-small waves-effect waves-light blue"><i class="material-icons">remove</i></a>
                </li>
            }
        </ul>
        <br><br>
      </div>
    </div>
</div>